# LambdaTest Configuration

# Project and folder configuration
project_id: "01KGKNWGR465CDVXCCQSMP2SBC"
folder_id: "01KGKNWGXXBPN41P3ANMVBYGN9"

# Test Run configuration
assignee: 3153759
environment_id: 237997

Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
