# LambdaTest Configuration

# Project and folder configuration
project_id: "01KKVG6QCFB55AHCFNHA73WPE8"
folder_id: "01KKVG76Q5MP5XQ04WYCZZ6QZK"

# Test Run configuration
assignee: 3153759
environment_id: 2

#Test URL for automation
test_url: "https://demo.lambdatestinternal.com"
